# Generated by Django 6.0.6 on 2026-06-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="user",
            name="nome",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nome completo"
            ),
        ),
    ]
