# Generated by Django 6.0.6 on 2026-06-17 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_department_icon_organizationinvite"),
        ("tickets", "0002_ticketcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="organizations.department",
            ),
        ),
    ]
