# Generated by Django 4.2 on 2026-06-17 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_alter_ticket_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='department',
            new_name='old_department',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='assignee',
            new_name='old_assignee',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='old_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_tickets', to='organizations.department'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='old_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='organizations.department'),
        ),
    ]
