# Generated by Django 4.2 on 2026-06-17 15:10

from django.db import migrations

def migrate_ticket_data_forward(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    for ticket in Ticket.objects.all():
        if ticket.old_assignee:
            ticket.assignees.add(ticket.old_assignee)
        if ticket.old_department:
            ticket.departments.add(ticket.old_department)

def migrate_ticket_data_backward(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    for ticket in Ticket.objects.all():
        first_assignee = ticket.assignees.first()
        if first_assignee:
            ticket.old_assignee = first_assignee
        first_department = ticket.departments.first()
        if first_department:
            ticket.old_department = first_department
        ticket.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_assignee_and_department'),
    ]

    operations = [
        migrations.RunPython(migrate_ticket_data_forward, migrate_ticket_data_backward),
    ]
