# Generated by Django 4.2 on 2026-06-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_data_migration_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='old_assignee',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='old_department',
        ),
    ]
